### ISSUE TITLE
Api use in Android Application 

### ISSUE THREAD

**Issue by pavelsust** [prime-optimus/cricinfo-unofficial#2]
Hi, 
You done very well.I am searching like this api. I am new in Android Application Development. How i can use it into my Application for live score and Match schedule. If you provide a same app for using your api then it will be very pleaser for us.
Thanks

**Comment by prime-optimus** [comment]
Hi cepvirus,

Thanks for the appreciation. As far as use in an Android app is considered, this API, like other RESTful APIs, is really easy to use. You can pick up any Android tutorial about consuming RESTful APIs and you'll be good to start developing an app.

Regards.
